### PR TITLE
Fix windows on visible and dialog on open

### LINKED ISSUE #4805: Clicking "Disable Snap to Grid" resizes the main window (using multiple windows)
Strange regression in v1.3.10 reported in: https://community.aseprite.org/t/23912

### PR DESCRIPTION
**Pull request by martincapello**
Fix #4805 (`Window::onVisible()` not taking into account if the display was owned)
and https://community.aseprite.org/t/dialog-show-bounds-rectangle-is-broken-in-1-3-10/23917 (`DialogWindow::onOpen()` not calling `Window::onOpen()`)

### CODE REVIEW

File: src/app/script/dialog_class.cpp [hunk 1]
```diff
@@ -78,6 +78,7 @@ class DialogWindow : public WindowWithHand {
     if (m_handTool && Editor::activeEditor()) {
       enableHandTool(true);
     }
+    Window::onOpen(ev);
```
Comment (dacap) [inline src/app/script/dialog_class.cpp:81]: Should be `WindowWithHand::onOpen()`

Comment (martincapello) [reply src/app/script/dialog_class.cpp:81]: Damn, give me a min
