### PR TITLE
Fix Magic Wand doesn't work correctly in Tiled Mode (fix #4659)

### LINKED ISSUE #4659: Magic Wand doesn't work correctly in Tiled Mode
In Tiled Mode, Magic Wand works only when we click in the top-left ninth:

Peek 2024-09-12 19-20

From: https://community.aseprite.org/t/i-cant-select-with-the-magic-wand-tool/23399/6?u=dacap

### PR DESCRIPTION
**Pull request by Gasparoken**
fix #4659

### CODE REVIEW

File: src/app/ui/editor/tool_loop_impl.cpp [hunk 1]
```diff
@@ -360,6 +360,15 @@ class ToolLoopBase : public tools::ToolLoop {
             == app::gen::PixelConnectivity::EIGHT_CONNECTED);
   }
 
+  bool isPointInsideTheCanvas(const gfx::Point& point) override {
```
Comment (martincapello) [inline src/app/ui/editor/tool_loop_impl.cpp:363]: Just a minor thing, I think I would rename this as isPointInsideCanvas().

**Review by martincapello — APPROVED** [review]
Works great! I just did a minor comment, feel free to omit it if you like the name as is.

**Comment by dacap** [comment]
Works great!
