### PR TITLE
Fix hidden layers affect z-index (fix #5681)

### LINKED ISSUE #5681: Hidden layers affect z-index
Reported here: https://community.aseprite.org/t/z-index-poor-solution/28085/1

### PR DESCRIPTION
**Pull request by Gasparoken**
fix #5681

### CODE REVIEW

File: src/render/render.cpp [hunk 1]
```diff
@@ -1,6 +1,6 @@
 // Aseprite Render Library
-// Copyright (C) 2019-2025  Igara Studio S.A.
-// Copyright (C) 2001-2018  David Capello
+// Copyright (C) 2019-present  Igara Studio S.A.
+// Copyright (C) 2001-2018     David Capello
```
Comment (dacap) [inline src/render/render.cpp]: No need to align these lines.

File: src/render/render.cpp [hunk 2]
```diff
@@ -1130,10 +1130,8 @@ void Render::renderPlan(RenderPlan& plan,
 
         RenderPlan subPlan(m_composeGroups);
 
-        for (const Layer* child : static_cast<const LayerGroup*>(layer)->layers()) {
-          if (child->isVisible())
-            subPlan.addLayer(child, frame);
-        }
+        for (const Layer* child : static_cast<const LayerGroup*>(layer)->layers())
```
Comment (dacap) [inline src/render/render.cpp]: You should be able to use
```suggestion
        for (const Layer* child : layer->layers())
```
As now (in beta branch) `doc::Layer` contains the `layers()`.

**Comment by dacap** [comment]
It's a shame that the `RenderPlan` includes the hidden layers in the final result. Probably after processing z-indexes we could remove all hidden layers (?).

**Comment by Gasparoken** [comment]
Test pending

**Comment by Gasparoken** [comment]
@dacap, this PR requires https://github.com/aseprite/aseprite/pull/5692 to run the z_order.lua tests correctly.
