### PR TITLE
Fix exporting a Sprite Sheet with Group name has different functionality between CLI and Scripting (fix #4456)

### LINKED ISSUE #4456: [bug] [scripting] Exporting a Sprite Sheet with Group name has different functionality between CLI and Scripting
Exporting a sprite sheet using the CLI has the expected behavior when specifying a group name. When using a lua script, the group name is lost and instead, all layers and groups are exported.

___

I have an aesprite file laid out as shown below. All of the layers share the same tagged sections.

> sprite.ase
> - group1
>   - layer1
>   - layer2
> - group2
>   - layer1
>   - layer2

Using the following cli command, I am able to export the correct layer:

`aseprite -b --sheet-type rows --split-tags --list-tags --split-layers --list-layers --layer "group1/layer2" --filename-format "{tag}_{tagframe00}" sprite.ase --sheet "group1_layer2.png" --data "group1_layer2.json"`

I want to export all layers without having to specify the names of each layer individually. Using a lua script for this is trivial, however, the `app.command.ExportSpriteSheet` does not behave correctly when passing a "group/layer" string into the layer parameter. It instead exports all layers concatenated into a single png and json file no matter what group / layer combo is specified.

```lua
app.command.ExportSpriteSheet({
    ui = false,
    askOverwrite = false,
    type = SpriteSheetType.ROWS,
    splitTags = true,
    listTags = true,
    splitLayers = true,
    listLayers = true,
    layer = "group1/layer2",
    filenameFormat = "{tag}_{tagframe00}",
    textureFilename = "group1_layer2.png",
    dataFilename = "group1_layer2.json",
})
```

___

Is there another way to export each layer as its own spritesheet without flattening my aseprite hierarchy? Currently the json matches (besides the meta object) since all layers share tags, so getting the pngs files is the problem.

### Aseprite and System version

* Aseprite version: Aseprite 1.x-dev
* System: Windows 11 x64

### PR DESCRIPTION
**Pull request by Gasparoken**
fix #4456

### CODE REVIEW

File: tests/scripts/app_command.lua [hunk 1]
```diff
@@ -99,6 +99,21 @@ do -- ExportSpriteSheet
...
+    textureFilename="_test_export_spritesheet4.png",
+    layer="G1/G2/G3/b",
+    trim=true,
+  }
+  local i = Image{ fromFile="_test_export_spritesheet4.png" }
+  expect_img(i,  {
+    c,c,0,
+    c,c,0,
+    c,c,c,
+  })
```
Comment (dacap) [inline tests/scripts/app_command.lua:116]: I think we can use `groups3abc.aseprite` and `groups4.aseprite` from this patch:
```suggestion

  local s = Sprite{ fromFile="sprites/groups3abc.aseprite" }
  local c = app.pixelColor.rgba(75, 105, 47)
  app.command.ExportSpriteSheet {
    type=SpriteSheetType.ROWS,
    textureFilename="_test_export_spritesheet4.png",
    layer="b/b",
    trim=true,
  }
  local i = Image{ fromFile="_test_export_spritesheet4.png" }
  expect_img(i,  {
    c,c,0,
    c,c,0,
    c,c,c,
  })
```

**Review by dacap — CHANGES_REQUESTED** [review]
Several comments/changes to make and it breaks the filtering of specific sublayers. Current behavior:

https://github.com/aseprite/aseprite/assets/39654/e8017ee3-4e22-4026-bad8-67526272db9d

With this patch:

https://github.com/aseprite/aseprite/assets/39654/7acf5999-200f-4844-a726-895b538d70bb

Please dedicate more time to test your PRs.

**Comment by Gasparoken** [comment]
Ready for review. @dacap I can squash the commits at the end of the review, or now, if that's better for you.
