### PR TITLE
Fix file selector not allowing choosing files by path

### LINKED ISSUE #2228: Can't select file by full path on Linux
### Aseprite and System version

* Aseprite version: v1.2.16.3
* System: Linux

When I want to choose a file, if I type in the full path, like `/tmp/test.png`, it will say:

image

This should not happen.

### PR DESCRIPTION
**Pull request by Adrijaned**
Fixes #2228 
Previously was treating path entered into the file selector either as path to a directory, or as a name of the file in current directory. Now allows also for entering path to the file, both relative and absolute.

### CODE REVIEW

**Comment by Adrijaned** [comment]
I believe this also fixes #2233

**Comment by dacap** [comment]
Hi @Adrijaned, thanks for your contribution, I'll try to take to this issue ASAP in this week.

File: src/app/ui/file_selector.cpp [hunk 1]
```diff
@@ -613,38 +613,33 @@ bool FileSelector::show(
...
-
-      // show the window again
-      setVisible(true);
-      goto again;
+    // check if the filename doesn't contain ilegal characters...
+    // Only if it does not exist
+    // Only on Windows, Linux disallows only `/`, and we can consider that just an embedded path if present
+    if (!enter_folder) {
+      bool has_invalid_char =
+         fn.find(':') != std::string::npos ||
```
Comment (dacap) [inline src/app/ui/file_selector.cpp]: There is a missing `(`, anyway I'll check if I can add support to use full paths on Windows too.
```suggestion
        (fn.find(':') != std::string::npos ||
```

**Comment by dacap** [comment]
Thanks @Adrijaned, we've merged your PR!
