### PR TITLE
Fix entry's selected text background drawing

### LINKED ISSUE #5520: Choppy selected text on entry widgets
The selected text in entry widgets is showed as all choppy when the selected font is not spritesheet based and their glyphs overlap to each other.
For instance, using the "Apple Chancery" font in macOS:

Image

### PR DESCRIPTION
**Pull request by martincapello**
Fix #5520

This PR requires https://github.com/aseprite/laf/pull/163.

### CODE REVIEW

File: src/app/ui/skin/skin_theme.cpp [hunk 1]
```diff
@@ -1357,17 +1357,38 @@ class DrawEntryTextDelegate : public text::DrawTextDelegate {
...
+    gfx::Color bg = ColorNone;
+
+    if (m_widget->hasFocus())
+      bg = colors.selected();
+    else
+      bg = colors.disabled();
+
+    if (bg != ColorNone) {
+      gfx::Rect fillThisRect(bounds.x - m_widget->bounds().x, m_y, bounds.w, m_h);
+      m_graphics->fillRect(bg, fillThisRect);
```
Comment (dacap) [inline src/app/ui/skin/skin_theme.cpp]:
```suggestion
      m_graphics->fillRect(bg, gfx::Rect(bounds.x - m_widget->bounds().x, m_y, bounds.w, m_h));
```
