### PR TITLE
Fix error decoding pico-8 GIFs (fix #3922)

### LINKED ISSUE #3922: Error decoding pico-8 GIFs
Problems decoding gif files created from pico-8.

Reported here https://twitter.com/calixjumio/status/1667223925292408833
Internal ticket: https://igarastudio.zendesk.com/agent/tickets/4880

I have created a GIF to with pico-8 to reproduce this bug:

untitled_4

### PR DESCRIPTION
**Pull request by Gasparoken**
fix #3922

### CODE REVIEW

File: src/app/file/gif_format.cpp [hunk 1]
```diff
@@ -492,177 +492,160 @@ class GifDecoder {
...
+          0 <= m_localTransparentIndex &&
+          m_localTransparentIndex < usedEntries.size() &&
+          m_frameNum > 0) {
+        usedEntries[m_localTransparentIndex] = false;
+      }
+      // A sprite with transparent layer always needs a defined transparent
+      // entry to be able to represent transparent color.
+      // If the GIF is identified as a transparent sprite, we'll be forced
+      // to adopt a transparent entry (no matter if the sprite will end
+      // with all opaqe pixels).
```
Comment (martincapello) [inline src/app/file/gif_format.cpp:542]: Typo, should be "opaque"

**Review by martincapello — APPROVED** [review]
Looks good to me. Just found a typo in a comment.

**Comment by Gasparoken** [comment]
Ready for review @dacap.
