### PR TITLE
Fix crash applying filters (fix #4928)

### LINKED ISSUE #4928: New crash applying filters (?)
Steps to reproduce:
1. Create a new RGB sprite.
2. Draw something using just 1 color.
3. Go to Replace Color filter.
4. Replace the color just used by the Mask color.
5. Press "Apply" or "Ok" button --> Crash.

The same happens if we draw something using several colors and then using the Replace Color filter we replace each color by the Mask color using the "Apply" button. When the last color is replaced it crashes as well.

Sentry Issue: [ASEPRITE-2V7](https://igara-studio.sentry.io/issues/6205317225/?referrer=github_integration)

```
OS Version: Windows 10.0.19045 (5247)
Report Version: 104

Crashed Thread: 7588

Application Specific Information:
Fatal Error: EXCEPTION_ACCESS_VIOLATION_READ / 0x18

Thread 7588 Crashed:
0   Aseprite.exe                    0x7ff668827180      doc::Cel::sprite (cel.cpp:113)
1   Aseprite.exe                    0x7ff66845b337      app::crop_cel_image (cel_ops.cpp:275)
2   Aseprite.exe                    0x7ff6686c32df      app::FilterManagerImpl::init (filter_manager_impl.cpp:447)
3   Aseprite.exe                    0x7ff6686c1f12      app::FilterManagerImpl::apply (filter_manager_impl.cpp:254)
4   Aseprite.exe                    0x7ff6686c2679      app::FilterManagerImpl::applyToTarget (filter_manager_impl.cpp:306)
5   Aseprite.exe                    0x7ff6686c49fa      app::FilterWorker::applyFilterInBackground (filter_worker.cpp:189)
6   Aseprite.exe                    0x7ff6686c3e40      [inlined] app::FilterWorker::run::__l5::<lambda>::operator() (filter_worker.cpp:128)
7   Aseprite.exe                    0x7ff6686c3e40      [inlined] std::invoke (type_traits:1695)
8   Aseprite.exe                    0x7ff6686c3e40      std::thread::_Invoke<T> (thread:60)
9   Aseprite.exe                    0x7ff668a9dc9a      thread_start<T> (thread.cpp:97)
10  KERNEL32.DLL                    0x7ffe85547373      BaseThreadInitThunk
11  ntdll.dll                       0x7ffe86ffcc90      RtlUserThreadStart

Thread 9620 name: main
0   win32u.dll                      0x7ffe84b6a104      ZwUserMsgWaitForMultipleObjectsEx
1   USER32.dll                      0x7ffe86280c8d      RealMsgWaitForMultipleObjectsEx
2   Aseprite.exe                    0x7ff6688d9204      os::EventQueueWin::getEvent (event_queue.cpp:49)
3   Aseprite.exe                    0x7ff6688877f4      ui::Manager::generateMessagesFromOSEvents (manager.cpp:438)
4   Aseprite.exe                    0x7ff668887611      ui::Manager::generateMessages (manager.cpp:356)
5   Aseprite.exe                    0x7ff6688b6820      ui::MessageLoop::pumpMessages (message_loop.cpp:24)
6   Aseprite.exe                    0x7ff668885d5d      ui::Manager::_runModalWindow (manager.cpp:1571)
7   Aseprite.exe                    0x7ff668881543      ui::Window::openWindowInForeground (window.cpp:394)
8   Aseprite.exe                    0x7ff6686c4d53      [inlined] app::`anonymous-namespace'::FilterWorkerAlert::openAndWait (filter_worker.cpp:53)
9   Aseprite.exe                    0x7ff6686c4d53      app::FilterWorker::run (filter_worker.cpp:129)
10  Aseprite.exe                    0x7ff6686c4f20      app::FilterManagerImpl::startWorker (filter_worker.cpp:223)
11  Aseprite.exe                    0x7ff6686c6278      app::FilterWindow::doModal (filter_window.cpp:125)
12  Aseprite.exe                    0x7ff668547e58      app::ReplaceColorCommand::onExecute (cmd_replace_color.cpp:199)
13  Aseprite.exe                    0x7ff66833dddc      app::Context::executeCommand (context.cpp:196)
14  Aseprite.exe                    0x7ff66833ded2      app::Context::executeCommandFromMenuOrShortcut (context.cpp:165)
15  Aseprite.exe                    0x7ff668421d03      app::CustomizedGuiManager::processKey (gui.cpp:737)
16  Aseprite.exe                    0x7ff6684212df      app::CustomizedGuiManager::onProcessMessage (gui.cpp:556)
17  Aseprite.exe                    0x7ff66887a0cb      [inlined] ui::Widget::onProcessMessage (widget.cpp:1656)
18  Aseprite.exe                    0x7ff66887a0cb      [inlined] ui::Widget::onProcessMessage (widget.cpp:1656)
19  Aseprite.exe                    0x7ff66887a0cb      ui::Widget::onProcessMessage (widget.cpp:1656)
20  Aseprite.exe                    0x7ff668895d05      ui::Splitter::onProcessMessage (splitter.cpp:183)
21  Aseprite.exe                    0x7ff66887a0cb      [inlined] ui::Widget::onProcessMessage (widget.cpp:1656)
22  Aseprite.exe                    0x7ff66887a0cb      [inlined] ui::Widget::onProcessMessage (widget.cpp:1656)
23  Aseprite.exe                    0x7ff66887a0cb      ui::Widget::onProcessMessage (widget.cpp:1656)
24  Aseprite.exe                    0x7ff668895d05      ui::Splitter::onProcessMessage (splitter.cpp:183)
25  Aseprite.exe                    0x7ff66887a0cb      [inlined] ui::Widget::onProcessMessage (widget.cpp:1656)
26  Aseprite.exe                    0x7ff66887a0cb      [inlined] ui::Widget::onProcessMessage (widget.cpp:1656)
27  Aseprite.exe                    0x7ff66887a0cb      [inlined] ui::Widget::onProcessMessage (widget.cpp:1656)
28  Aseprite.exe                    0x7ff66887a0cb      [inlined] ui::Widget::onProcessMessage (widget.cpp:1656)
29  Aseprite.exe                    0x7ff66887a0cb      [inlined] ui::Widget::onProcessMessage (widget.cpp:1656)
30  Aseprite.exe                    0x7ff66887a0cb      [inlined] ui::Widget::onProcessMessage (widget.cpp:1656)
31  Aseprite.exe                    0x7ff66887a0cb      ui::Widget::onProcessMessage (widget.cpp:1656)
32  Aseprite.exe                    0x7ff6683c2650      app::Editor::onProcessMessage (editor.cpp:2247)
33  Aseprite.exe                    0x7ff668634aaf      app::`anonymous namespace'::AppEditor::onProcessMessage (doc_view.cpp:166)
34  Aseprite.exe                    0x7ff66888a4a8      ui::Manager::sendMessageToWidget (manager.cpp:1959)
35  Aseprite.exe                    0x7ff668889bf8      ui::Manager::pumpQueue (manager.cpp:1836)
36  Aseprite.exe                    0x7ff66888663d      ui::Manager::dispatchMessages (manager.cpp:851)
37  Aseprite.exe                    0x7ff66888a329      ui::Manager::run (manager.cpp:304)
38  Aseprite.exe                    0x7ff6682b22eb      app::App::run (app.cpp:565)
39  Aseprite.exe                    0x7ff6682a9aa6      app_main (main.cpp:138)
40  Aseprite.exe                    0x7ff668afee44      wWinMain (main.cpp:40)
41  Aseprite.exe                    0x7ff668a5bf15      [inlined] invoke_main (exe_common.inl:118)
42  Aseprite.exe                    0x7ff668a5bf15      __scrt_common_main_seh (exe_common.inl:288)
43  KERNEL32.DLL                    0x7ffe85547373      BaseThreadInitThunk
44  ntdll.dll                       0x7ffe86ffcc90      RtlUserThreadStart
```

### PR DESCRIPTION
**Pull request by martincapello**
Prevents the program from crashing when applying a filter that as a result removes the current cel. Fix #4928 
Also, this PR introduces the `ui::execute_now_or_enqueue` function that is used in `Timeline::onAfterRemoveCel` to avoid this assert:
https://github.com/aseprite/aseprite/blob/5e6927ed4e362c42ce8a3aecb62e6f64a3c8a5a5/src/app/pref/preferences.cpp#L31-L36

That is reached by the following call stack of the filter worker thread (hence it is called from outside the main thread):

```
ui::assert_ui_thread() (src/ui/system.cpp:299)
app::Preferences::instance() (src/app/pref/preferences.cpp:35)
app::Timeline::docPref() const (src/app/ui/timeline/timeline.cpp:4278)
app::Timeline::zoom() const (src/app/ui/timeline/timeline.cpp:4318)
app::Timeline::layerBoxHeight() const (src/app/ui/timeline/timeline.cpp:4298)
app::Timeline::getPartBounds(app::Timeline::Hit const&) const (src/app/ui/timeline/timeline.cpp:3029)
app::Timeline::invalidateLayer(doc::Layer const*) (src/app/ui/timeline/timeline.cpp:3257)
app::Timeline::onAfterRemoveCel(app::DocEvent&) (src/app/ui/timeline/timeline.cpp:1962)
void obs::observers<app::DocObserver>::notify_observers<app::DocEvent&>(void (app::DocObserver::*)(app::DocEvent&), app::DocEvent&) (src/observable/obs/observers.h:37)
void obs::observable<app::DocObserver>::notify_observers<app::DocEvent&>(void (app::DocObserver::*)(app::DocEvent&), app::DocEvent&) (src/observable/obs/observable.h:33)
app::cmd::AddCel::removeCel(doc::Layer*, doc::Cel*) (src/app/cmd/add_cel.cpp:113)
app::cmd::AddCel::onUndo() (src/app/cmd/add_cel.cpp:61)
app::cmd::RemoveCel::onExecute() (src/app/cmd/remove_cel.cpp:26)
app::Cmd::execute(app::Context*) (src/app/cmd.cpp:39)
app::CmdSequence::onExecute() (src/app/cmd_sequence.cpp:58)
app::Cmd::execute(app::Context*) (src/app/cmd.cpp:39)
```

It should also avoid crashed by avoiding the access of the Preferences std::map<> from outside the main thread, as the comment says.

### CODE REVIEW

File: src/app/ui/timeline/timeline.cpp [hunk 1]
```diff
@@ -1958,7 +1958,7 @@ void Timeline::onAddCel(DocEvent& ev)
 
 void Timeline::onAfterRemoveCel(DocEvent& ev)
 {
-  invalidateLayer(ev.layer());
+  ui::execute_now_or_enqueue([this, &ev] { invalidateLayer(ev.layer()); });
```
Comment (dacap) [inline src/app/ui/timeline/timeline.cpp:1961]: Make a copy of the DocEvent parameter because it's a local variable and might not exist in the UI thread later:
```suggestion
  ui::execute_now_or_enqueue([this, ev] { invalidateLayer(ev.layer()); });
```

**Review by dacap — CHANGES_REQUESTED** [review]
LGTM, just a minor change in the comments.

It's also related to #378 in some way, because in a future we should find a better way to update the UI from doc changes, and avoid this situation where observers are called from a background thread (same can happen with script events).

File: src/app/ui/timeline/timeline.cpp (hunk 1 above)
Comment (martincapello) [reply src/app/ui/timeline/timeline.cpp:1961]: You are right! Thanks!
