### PR TITLE
Fix wrong export of tileset (fix #5053)

### LINKED ISSUE #5053: Wrong export of tileset
**Version**: Aseprite v1.3.13-x64 (Linux)
**Sample file**: https://code.ffreling.com/fabs/rush/raw/commit/4a6437c32306e09efb1977e815af586b32778abf/src/img/level_01.ase

I want to export a tileset via the CLI but the result is wrong, whereas it looks ok doing it through the GUI.
I exported with this command : `aseprite -b --export-tileset level_01.ase --sheet level_01.png`. Through the GUI, all options seem to work fine.

| CLI (wrong)  | GUI (correct) |
| ------------- | ------------- |
| Image | Image |

For context, my image is made for Playdate and is only made of black & white pixel.

### PR DESCRIPTION
**Pull request by Gasparoken**
fix #5053

### CODE REVIEW

**Review by martincapello — APPROVED** [review]
LGTM! Just needs a rebase and I think that's it.

**Comment by Gasparoken** [comment]
Just rebased.

File: laf
Comment (dacap) [inline laf:1]: Can we remove this laf change?

File: src/app/doc_exporter.cpp [hunk 1]
```diff
@@ -1228,6 +1231,36 @@ Doc* DocExporter::createEmptyTexture(const Samples& samples, base::task_token& t
...
+                                 convertedImg.get(),
+                                 newPixelFormat,
+                                 dithering,
+                                 sprite ? sprite->rgbMap(0) : nullptr,
+                                 sprite ? sprite->palette(0) : nullptr,
+                                 sprite ? sprite->backgroundLayer() : nullptr,
+                                 0,
+                                 0,
+                                 nullptr);
+    sample.image() = std::move(convertedImg);
```
Comment (dacap) [inline src/app/doc_exporter.cpp:1260]: It looks like we need a `Sample::setImage()` function, or even better: that we could add a `Sample::setPixelFormat()` function to the `Sample` class itself to delegate this work (and remove the `Sample::image()` function).

File: tests/cli/sheet.sh [hunk 2]
```diff
@@ -416,3 +416,38 @@ t = tags["tags3-reverse"]  assert(t.from == 4 and t.to == 7)
...
+  for i=0 , #ts-1 do
+    local tileImage = ts:getTile(i)
+    local offset = Point(origin.x + i*tileImage.width, origin.y)
+    for y=0 , tileImage.height-1 do
+      for x=0 , tileImage.width-1 do
+        assert(tileImage:getPixel(x, y) == sheetImage:getPixel(offset.x + x, offset.y + y))
+      end
+    end
+  end
+end
```
Comment (dacap) [inline tests/cli/sheet.sh:450]: Minor style change (don't add a space before each comma in for statements):
```suggestion
for k=1, #filenames do
  local spr = Sprite{ fromFile=filenames[k] }
  if spr.colorMode ~= spriteSheet.colorMode then
    app.sprite = spr
    app.command.ChangePixelFormat { format="rgb" }
  end
  local ts = spr.layers[1].tileset
  local origin = origins[k]
  for i=0, #ts-1 do
    local tileImage = ts:getTile(i)
    local offset = Point(origin.x + i*tileImage.width, origin.y)
    for y=0, tileImage.height-1 do
      for x=0, tileImage.width-1 do
        assert(tileImage:getPixel(x, y) == sheetImage:getPixel(offset.x + x, offset.y + y))
      end
    end
  end
end
```

**Review by dacap — CHANGES_REQUESTED** [review]

File: src/app/doc_exporter.cpp (hunk 1 above)
Comment (Gasparoken) [reply src/app/doc_exporter.cpp]: You right! Thanks
