### PR TITLE
Fix wrong edges on Brush Preview on Tilemap Mode (fix #4176)

### LINKED ISSUE #4176: Wrong edges on Brush Preview on Tilemap Mode
When 'Edges' are active on 'Brush Preview' + 'Tilemap Mode', the edges of the regular brush is displayed instead the bounds of the tile.

### Aseprite and System version

* Aseprite version: 1.3

### PR DESCRIPTION
**Pull request by Gasparoken**
fix #4176

### CODE REVIEW

**Review by martincapello — APPROVED** [review]
Have been testing this for a bit and seems to work fine!

**Comment by Gasparoken** [comment]
The only thing I'm not sure about is when dynamics are enabled:
There are several options for this:
1. Always show the brush edges that correspond to the maximum size (like the current solution).
2. Don't show brush edges when Dynamics are enabled.
3. Show the brush edges as fast as the brush display changes due to Dynamics (I think this would have no real practical use and may introduce render lags because of this).
4. The brush edges corresponding to the maximum size are displayed while the brush is not drawing, then the brush edges disappear during the drawing state.
5. Other?

Personally, I'd like option 1 or 2.
What do you think @martincapello?

File: src/app/ui/editor/brush_preview.cpp [hunk 1]
```diff
@@ -262,6 +260,8 @@ void BrushPreview::show(const gfx::Point& screenPos)
           if (showPreview)
             showPreviewWithEdges = true;
           m_type = BRUSH_BOUNDARIES;
+          if (tilemapMode == TilemapMode::Tiles)
+            m_type |= CROSSHAIR;
```
Comment (dacap) [inline src/app/ui/editor/brush_preview.cpp:264]: This should be valid for `app::gen::BrushPreview::EDGES` case too to avoid this bug:

edges-only

My recommended change, remove these lines:

```suggestion
```

And add after the `switch`:

```c++
  // For tiles as we show the edges of the tile, we add the crosshair
  // in the mouse position as a helper.
  if (m_type & BRUSH_BOUNDARIES &&
      tilemapMode == TilemapMode::Tiles) {
    m_type |= CROSSHAIR;
  }
```

File: src/app/ui/editor/brush_preview.cpp [hunk 2]
```diff
@@ -165,11 +163,14 @@ void BrushPreview::show(const gfx::Point& screenPos)
 
   tools::Tool* tool = m_editor->getCurrentEditorTool();
   const bool isFloodfill = tool->getPointShape(0)->isFloodFill();
-  // TODO add support for "tile-brushes"
+
+  // Get current tilemap mode
+  TilemapMode tilemapMode = site.tilemapMode();
```
Comment (dacap) [inline src/app/ui/editor/brush_preview.cpp:168]: A little nice change is to put this as `const`:
```suggestion
  const TilemapMode tilemapMode = site.tilemapMode();
```
This indicates that the `tilemapMode` is used just like a constant value/an alias of `site.tilemapMode()`. (There are a lot of missing `const` in the code, so there is no problem if this is added or not).

File: src/app/ui/editor/brush_preview.cpp [hunk 3]
```diff
@@ -512,13 +515,37 @@ void BrushPreview::invalidateRegion(const gfx::Region& region)
...
+                                                 const gfx::Point& spritePos)
+{
+  m_brushBoundaries.offset(-m_brushBoundaries.begin()[0].bounds().x,
+                           -m_brushBoundaries.begin()[0].bounds().y);
+  gfx::Point canvasPos = grid.tileToCanvas(grid.canvasToTile(spritePos));
+  m_brushBoundaries.offset(canvasPos.x - spritePos.x,
+                           canvasPos.y - spritePos.y);
+}
+
+void BrushPreview::generateBoundaries(Site &site, gfx::Point spritePos)
```
Comment (dacap) [inline src/app/ui/editor/brush_preview.cpp:528]: To avoid a copy of the `Site` we can use a `const Site&`:
```suggestion
void BrushPreview::generateBoundaries(const Site& site,
                                      const gfx::Point& spritePos)
```

File: src/app/ui/editor/brush_preview.h [hunk 4]
```diff
@@ -10,6 +10,7 @@
 #pragma once
 
 #include "app/extra_cel.h"
+#include "app/site.h"
```
Comment (dacap) [inline src/app/ui/editor/brush_preview.h:13]: Not required as we are not using the `Site` value/size:
```suggestion
```
You can add a forward declaration below after `  class Editor;` line:
```c++
namespace app {
  class Editor;
  class Site;  // <--

  class BrushPreview ...
```

File: src/app/ui/editor/brush_preview.h [hunk 5]
```diff
@@ -90,7 +91,12 @@ namespace app {
     doc::BrushRef getCurrentBrush();
     static doc::color_t getBrushColor(doc::Sprite* sprite, doc::Layer* layer);
 
-    void generateBoundaries();
+    // Offset re-calculation of brush boundaries only for TilemapMode::Tiles.
+    // Used within 'generateBoundaries' function.
+    void calculateTileBoundariesOrigin(const doc::Grid& grid,
+                                       const gfx::Point& spritePos);
+
+    void generateBoundaries(Site &site, gfx::Point spritePos);
```
Comment (dacap) [inline src/app/ui/editor/brush_preview.h:99]:
```suggestion
    void generateBoundaries(const Site& site,
                            const gfx::Point& spritePos);
```

File: src/app/ui/editor/brush_preview.h [hunk 6]
```diff
@@ -141,6 +147,9 @@ namespace app {
     gfx::Rect m_lastBounds;
     doc::frame_t m_lastFrame;
 
+    doc::Layer* m_lastLayer;
```
Comment (dacap) [inline src/app/ui/editor/brush_preview.h:150]:
```suggestion
    doc::Layer* m_lastLayer = nullptr;
```

**Review by dacap — CHANGES_REQUESTED** [review]
It works great 👍 there are just some minor changes required.

File: src/app/ui/editor/brush_preview.cpp (hunk 3 above)
Comment (Gasparoken) [reply src/app/ui/editor/brush_preview.cpp:528]: Thanks! You added `const` to lock the values of the `Site` object inside the `generateBoundaries` function.
And you corrected `Site &site` as `Site& site` (I used to think `Site &site` is the same as `Site& site` @dacap could you confirm this?).

Comment (dacap) [reply src/app/ui/editor/brush_preview.cpp:528]: Sorry my first comment about "to avoid a copy" was wrong for `Site` (it was for `gfx::Point`) as originally it was `Site& site`, not `Site site`. (When we use value parameters like `Site site` is when a copy is made, I read it wrong when wrote that comment.)

About `Site &site` vs `Site& site` there is no difference, it's just the formatting we are using and we have to keep it consistent.

Comment (Gasparoken) [reply src/app/ui/editor/brush_preview.cpp]: Oh! `gfx::Point`, I omitted to modify it. I pushed a new change to include `const gfx::Point&`.
Thanks for the clarification!
