### PR TITLE
Fx Alt+T -> Alt+V instantly crashes Aseprite without warning (fix #4221)

### LINKED ISSUE #4221: Alt+T -> Alt+V instantly crashes Aseprite without warning
Reported here:

https://steamcommunity.com/app/431730/discussions/2/4034725980842866910/

### PR DESCRIPTION
**Pull request by Gasparoken**
First approach.

fix #4221

### CODE REVIEW

File: src/ui/menu.cpp [hunk 1]
```diff
@@ -630,6 +645,15 @@ bool MenuBox::onProcessMessage(Message* msg)
...
       if (menu) {
+        MenuItem* child_with_submenu_opened = nullptr;
+        findChildWithSubmenuOpened(menu, child_with_submenu_opened);
+        if (child_with_submenu_opened &&
+            child_with_submenu_opened->inBar() &&
+            this->type() == kMenuBarWidget &&
+            msg->modifiers() == kKeyAltModifier) {
+          cancelMenuLoop();
+        }
+
```
Comment (martincapello) [inline src/ui/menu.cpp:656]: I've been testing the fix and it works great. The only thing I'm not sure about is this piece of code, which I couldn't figure out how to make this if condition true. I also tested the fix without this code and it seems to work as well. So I would love to know what I am missing here.

**Review by martincapello — COMMENTED** [review]
The fix works as expected, but I would need some clarification about an if condition.

File: src/ui/menu.cpp (hunk 1 above)
Comment (Gasparoken) [reply src/ui/menu.cpp]: You're right! Thank you!

**Review by martincapello — APPROVED** [review]
