### PR TITLE
Revert wrapping MouseEnter/Leave messages into CallbackMessages

### LINKED ISSUE #4754: New crash/regression now that kCallbackMessage is correctly processed
The #4718 fix (which now properly calls the callback function) introduced some kind of crash just dragging/clicking the mouse in a combobox: 

https://github.com/user-attachments/assets/12698f7b-b144-4112-8d4d-d0e166f136d7

Sanitizer output:

```
=================================================================
==2559==ERROR: AddressSanitizer: heap-use-after-free on address 0x60b0003f71c8 at pc 0x000100de83a4 bp 0x00016f569e40 sp 0x00016f569e38
READ of size 8 at 0x60b0003f71c8 thread T0
    #0 0x100de83a0 in base::Ref<os::Window>::get() const ref.h:100
    #1 0x100de8118 in ui::Display::nativeWindow() const display.h:33
    #2 0x102fe0790 in ui::set_native_cursor_on_all_displays(ui::Display*, os::NativeCursor) system.cpp:112
    #3 0x102fdeac8 in ui::update_mouse_cursor() system.cpp:181
    #4 0x102fde264 in ui::_internal_set_mouse_display(ui::Display*) system.cpp:255
    #5 0x102f4d130 in ui::Manager::generateMessagesFromOSEvents()::$_0::operator()() const manager.cpp:495
    #6 0x102f4d018 in decltype(std::declval<ui::Manager::generateMessagesFromOSEvents()::$_0&>()()) std::__1::__invoke[abi:ne180100]<ui::Manager::generateMessagesFromOSEvents()::$_0&>(ui::Manager::generateMessagesFromOSEvents()::$_0&) invoke.h:344
    #7 0x102f4cfd0 in void std::__1::__invoke_void_return_wrapper<void, true>::__call[abi:ne180100]<ui::Manager::generateMessagesFromOSEvents()::$_0&>(ui::Manager::generateMessagesFromOSEvents()::$_0&) invoke.h:419
    #8 0x102f4cfac in std::__1::__function::__alloc_func<ui::Manager::generateMessagesFromOSEvents()::$_0, std::__1::allocator<ui::Manager::generateMessagesFromOSEvents()::$_0>, void ()>::operator()[abi:ne180100]() function.h:169
    #9 0x102f48a14 in std::__1::__function::__func<ui::Manager::generateMessagesFromOSEvents()::$_0, std::__1::allocator<ui::Manager::generateMessagesFromOSEvents()::$_0>, void ()>::operator()() function.h:311
    #10 0x1008fb6dc in std::__1::__function::__value_func<void ()>::operator()[abi:ne180100]() const function.h:428
    #11 0x1008fb534 in std::__1::function<void ()>::operator()() const function.h:981
    #12 0x10305e9b4 in ui::CallbackMessage::call() message.h:92
    #13 0x10305e144 in ui::Widget::onProcessMessage(ui::Message*) widget.cpp:1609
    #14 0x102f3681c in ui::Manager::onProcessMessage(ui::Message*) manager.cpp:1672
    #15 0x101a666b8 in app::CustomizedGuiManager::onProcessMessage(ui::Message*) gui.cpp:606
    #16 0x10305b4a0 in ui::Widget::sendMessage(ui::Message*) widget.cpp:1339
    #17 0x102f3b2fc in ui::Manager::sendMessageToWidget(ui::Message*, ui::Widget*) manager.cpp:2017
    #18 0x102f2a79c in ui::Manager::pumpQueue() manager.cpp:1874
    #19 0x102f21e3c in ui::Manager::dispatchMessages() manager.cpp:857
    #20 0x102f95018 in ui::MessageLoop::pumpMessages() message_loop.cpp:26
    #21 0x102f35ea0 in ui::Manager::_runModalWindow(ui::Window*) manager.cpp:1604
    #22 0x10306bc34 in ui::Window::openWindowInForeground() window.cpp:405
    #23 0x10172b654 in app::SpritePropertiesCommand::onExecute(app::Context*) cmd_sprite_properties.cpp:393
    #24 0x1017bd61c in app::Command::execute(app::Context*) command.cpp:63
    #25 0x1018d2bc4 in app::Context::executeCommand(app::Command*, app::Params const&) context.cpp:183
    #26 0x1018d262c in app::Context::executeCommandFromMenuOrShortcut(app::Command*, app::Params const&) context.cpp:152
    #27 0x101c20254 in app::AppMenuItem::onClick() app_menuitem.cpp:149
    #28 0x102f70b6c in ui::MenuItem::onProcessMessage(ui::Message*) menu.cpp:1022
    #29 0x101c1f790 in app::AppMenuItem::onProcessMessage(ui::Message*) app_menuitem.cpp:107
    #30 0x10305b4a0 in ui::Widget::sendMessage(ui::Message*) widget.cpp:1339
    #31 0x102f3b2fc in ui::Manager::sendMessageToWidget(ui::Message*, ui::Widget*) manager.cpp:2017
    #32 0x102f2a79c in ui::Manager::pumpQueue() manager.cpp:1874
    #33 0x102f21e3c in ui::Manager::dispatchMessages() manager.cpp:857
    #34 0x102f95018 in ui::MessageLoop::pumpMessages() message_loop.cpp:26
    #35 0x102f2257c in ui::Manager::run() manager.cpp:286
    #36 0x1010872e8 in app::App::run() app.cpp:559
    #37 0x10089a8a4 in app_main(int, char**) main.cpp:152
    #38 0x103082f0c in main main.cpp:67
    #39 0x187310270  (<unknown module>)

0x60b0003f71c8 is located 8 bytes inside of 104-byte region [0x60b0003f71c0,0x60b0003f7228)
freed by thread T0 here:
    #0 0x107ad42d4 in _ZdlPv+0x74 (libclang_rt.asan_osx_dynamic.dylib:arm64e+0x642d4)
    #1 0x102f358cc in ui::Manager::_closeWindow(ui::Window*, bool) manager.cpp:1568
    #2 0x10306c118 in ui::Window::closeWindow(ui::Widget*) window.cpp:423
    #3 0x102e4d744 in ui::ComboBox::closeListBox() combobox.cpp:704
    #4 0x102e500b4 in ui::ComboBoxListBox::onProcessMessage(ui::Message*) combobox.cpp:597
    #5 0x10305b4a0 in ui::Widget::sendMessage(ui::Message*) widget.cpp:1339
    #6 0x102f3b2fc in ui::Manager::sendMessageToWidget(ui::Message*, ui::Widget*) manager.cpp:2017
    #7 0x102f2a79c in ui::Manager::pumpQueue() manager.cpp:1874
    #8 0x102f21e3c in ui::Manager::dispatchMessages() manager.cpp:857
    #9 0x102f95018 in ui::MessageLoop::pumpMessages() message_loop.cpp:26
    #10 0x102f35ea0 in ui::Manager::_runModalWindow(ui::Window*) manager.cpp:1604
    #11 0x10306bc34 in ui::Window::openWindowInForeground() window.cpp:405
    #12 0x10172b654 in app::SpritePropertiesCommand::onExecute(app::Context*) cmd_sprite_properties.cpp:393
    #13 0x1017bd61c in app::Command::execute(app::Context*) command.cpp:63
    #14 0x1018d2bc4 in app::Context::executeCommand(app::Command*, app::Params const&) context.cpp:183
    #15 0x1018d262c in app::Context::executeCommandFromMenuOrShortcut(app::Command*, app::Params const&) context.cpp:152
    #16 0x101c20254 in app::AppMenuItem::onClick() app_menuitem.cpp:149
    #17 0x102f70b6c in ui::MenuItem::onProcessMessage(ui::Message*) menu.cpp:1022
    #18 0x101c1f790 in app::AppMenuItem::onProcessMessage(ui::Message*) app_menuitem.cpp:107
    #19 0x10305b4a0 in ui::Widget::sendMessage(ui::Message*) widget.cpp:1339
    #20 0x102f3b2fc in ui::Manager::sendMessageToWidget(ui::Message*, ui::Widget*) manager.cpp:2017
    #21 0x102f2a79c in ui::Manager::pumpQueue() manager.cpp:1874
    #22 0x102f21e3c in ui::Manager::dispatchMessages() manager.cpp:857
    #23 0x102f95018 in ui::MessageLoop::pumpMessages() message_loop.cpp:26
    #24 0x102f2257c in ui::Manager::run() manager.cpp:286
    #25 0x1010872e8 in app::App::run() app.cpp:559
    #26 0x10089a8a4 in app_main(int, char**) main.cpp:152
    #27 0x103082f0c in main main.cpp:67
    #28 0x187310270  (<unknown module>)

previously allocated by thread T0 here:
    #0 0x107ad3e94 in _Znwm+0x74 (libclang_rt.asan_osx_dynamic.dylib:arm64e+0x63e94)
    #1 0x102f331b8 in ui::Manager::_openWindow(ui::Window*, bool) manager.cpp:1408
    #2 0x10306b990 in ui::Window::openWindow() window.cpp:391
    #3 0x102e51534 in ui::ComboBox::openListBox() combobox.cpp:685
    #4 0x102e4fd14 in ui::ComboBox::switchListBox() combobox.cpp:720
    #5 0x102e4f2e8 in ui::ComboBoxEntry::onProcessMessage(ui::Message*) combobox.cpp:509
    #6 0x10305b4a0 in ui::Widget::sendMessage(ui::Message*) widget.cpp:1339
    #7 0x102f3b2fc in ui::Manager::sendMessageToWidget(ui::Message*, ui::Widget*) manager.cpp:2017
    #8 0x102f2a79c in ui::Manager::pumpQueue() manager.cpp:1874
    #9 0x102f21e3c in ui::Manager::dispatchMessages() manager.cpp:857
    #10 0x102f95018 in ui::MessageLoop::pumpMessages() message_loop.cpp:26
    #11 0x102f35ea0 in ui::Manager::_runModalWindow(ui::Window*) manager.cpp:1604
    #12 0x10306bc34 in ui::Window::openWindowInForeground() window.cpp:405
    #13 0x10172b654 in app::SpritePropertiesCommand::onExecute(app::Context*) cmd_sprite_properties.cpp:393
    #14 0x1017bd61c in app::Command::execute(app::Context*) command.cpp:63
    #15 0x1018d2bc4 in app::Context::executeCommand(app::Command*, app::Params const&) context.cpp:183
    #16 0x1018d262c in app::Context::executeCommandFromMenuOrShortcut(app::Command*, app::Params const&) context.cpp:152
    #17 0x101c20254 in app::AppMenuItem::onClick() app_menuitem.cpp:149
    #18 0x102f70b6c in ui::MenuItem::onProcessMessage(ui::Message*) menu.cpp:1022
    #19 0x101c1f790 in app::AppMenuItem::onProcessMessage(ui::Message*) app_menuitem.cpp:107
    #20 0x10305b4a0 in ui::Widget::sendMessage(ui::Message*) widget.cpp:1339
    #21 0x102f3b2fc in ui::Manager::sendMessageToWidget(ui::Message*, ui::Widget*) manager.cpp:2017
    #22 0x102f2a79c in ui::Manager::pumpQueue() manager.cpp:1874
    #23 0x102f21e3c in ui::Manager::dispatchMessages() manager.cpp:857
    #24 0x102f95018 in ui::MessageLoop::pumpMessages() message_loop.cpp:26
    #25 0x102f2257c in ui::Manager::run() manager.cpp:286
    #26 0x1010872e8 in app::App::run() app.cpp:559
    #27 0x10089a8a4 in app_main(int, char**) main.cpp:152
    #28 0x103082f0c in main main.cpp:67
    #29 0x187310270  (<unknown module>)

SUMMARY: AddressSanitizer: heap-use-after-free ref.h:100 in base::Ref<os::Window>::get() const
Shadow bytes around the buggy address:
  0x60b0003f6f00: fd fd fd fd fd fd fd fd fd fd fd fd fd fd fa fa
  0x60b0003f6f80: fa fa fa fa fa fa fd fd fd fd fd fd fd fd fd fd
  0x60b0003f7000: fd fd fd fd fa fa fa fa fa fa fa fa fd fd fd fd
  0x60b0003f7080: fd fd fd fd fd fd fd fd fd fa fa fa fa fa fa fa
  0x60b0003f7100: fa fa fd fd fd fd fd fd fd fd fd fd fd fd fd fd
=>0x60b0003f7180: fa fa fa fa fa fa fa fa fd[fd]fd fd fd fd fd fd
  0x60b0003f7200: fd fd fd fd fd fa fa fa fa fa fa fa fa fa fd fd
  0x60b0003f7280: fd fd fd fd fd fd fd fd fd fd fd fd fa fa fa fa
  0x60b0003f7300: fa fa fa fa fd fd fd fd fd fd fd fd fd fd fd fd
  0x60b0003f7380: fd fd fa fa fa fa fa fa fa fa fd fd fd fd fd fd
  0x60b0003f7400: fd fd fd fd fd fd fd fd fa fa fa fa fa fa fa fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==2559==ABORTING
```

### PR DESCRIPTION
**Pull request by martincapello**
Changes reverted to fix #4754. We go back to the implementation without using CallbackMessages, the correct event's processing order is lost, but we have a fix for this in beta already, so once beta is merged into main, it will fix the processing order again.

### CODE REVIEW

File: src/ui/widget.cpp [hunk 1]
```diff
@@ -1592,8 +1592,8 @@ bool Widget::onProcessMessage(Message* msg)
       // Propagate the message to the parent.
       if (parent())
         return parent()->sendMessage(msg);
-      else
-        break;
+
+      break;
```
Comment (dacap) [inline src/ui/widget.cpp:1596]: Is this change necessary? I say this because it looks like a style/format unrelated change and when I merge this to beta I'll just ignore the change (as beta already contains another fix).

Comment (martincapello) [reply src/ui/widget.cpp:1596]: No, not at all. Just a small improvement, but if there are changes already, I will take it back right now.
