### PR TITLE
Fix Improve UX to recover files (fix #4130)

### LINKED ISSUE #4130: Improve UX to recover files
Sometimes we receive mails about how to recover a session file with the session folder compressed, and they follow this guide: https://www.aseprite.org/docs/data-recovery/

I'm not sure why the data recovery fails, if it's because the UI is confusing or if there is another kind of problem, because after decompressing the folder and giving a try to the same steps, we (generally) can recover the files from the same UI (without further assistance, something they could have done in the first place).

Even more, in some extreme case we could offer the way to get the compressed session folder from the same UI.

### PR DESCRIPTION
**Pull request by Gasparoken**
To implement this fix is needed https://github.com/aseprite/laf/pull/75 first

I think this solution can be improved on Windows since each session 'pid' is checked by iteratively searching all running processes in the operating system.

The best thing to do would be to create an array of 'pid' numbers belonging to running processes whose process name is 'aseprite.exe', then check to see if the 'pids' of each session match any element of the 'pid' array.

fix #4130

### CODE REVIEW

File: src/app/crash/session.cpp [hunk 1]
```diff
@@ -127,8 +127,12 @@ const Session::Backups& Session::backups()
 bool Session::isRunning()
 {
   loadPid();
+  std::string processName = "aseprite";
+  #if LAF_WINDOWS
+    processName = processName + ".exe";
+  #endif
   if (m_pid)
-    return base::is_process_running(m_pid);
+    return base::is_process_running(m_pid, processName.c_str());
```
Comment (martincapello) [inline src/app/crash/session.cpp:135]: I saw the changes in laf for supporting this and they look good. I'm just wondering if we should get the current process name instead of using a hardcoded string?

Comment (Gasparoken) [reply src/app/crash/session.cpp:135]: Yes! I agree with you.

**Comment by Gasparoken** [comment]
Tested on macOS and Windows. Ready for review.
