### PR TITLE
Fix multiple tileset layers selection move is broken (fix #3144)

### LINKED ISSUE #3144: Multiple tileset layers  selection move is broken
Hi all 👋 

I just found out that moving a selection in tileset mode having multiple tileset layers selected leads to loss of information. Only the last selected layers is moved, all the others are cleared (in the selection).

See an example here:
Screen Recording 2022-01-21 at 13 38 42

### Aseprite and System version

* Aseprite version: v1.3-beta10-dev compiled from the release archive
* System: macOS 12.1

### PR DESCRIPTION
**Pull request by Gasparoken**
Before this fix, a multi-layer mask movement/scaling (with mixed layer types: normal layer and tilemap layers with different grids) caused loss of drawing areas. The heart of this solution is to correctly align the 'selection mask' and 'transform data' according to the layer's grid, and also, forcing 'site' TilemapMode/TilesetMode before each reproduceAllTransformationsWithInnerCmds() iteration.

Additionally arrow keys now work to move a selected area in TilemapMode::Tiles.

fix aseprite/aseprite#3144

### CODE REVIEW

**Comment by Gasparoken** [comment]
This PR replaces https://github.com/aseprite/aseprite/pull/3205 and https://github.com/aseprite/aseprite/pull/3586

**Comment by dacap** [comment]
Copying [this comment](https://github.com/aseprite/aseprite/pull/3205#issuecomment-1270863852) just for reference to check if this issue was solved: As a side note this was merged in https://github.com/aseprite/aseprite/commit/bc050e8f15dbc71ac4cc64e84900820a5ecdd3b4 and then reverted https://github.com/aseprite/aseprite/commit/c08dc449013829b7d95b1b0a263b6100b52913ba because introduced the regression https://github.com/aseprite/aseprite/issues/3202

**Review by martincapello — APPROVED** [review]
Works great, just made a couple of minor comments.

File: src/app/ui/editor/pixels_movement.cpp [hunk 1]
```diff
@@ -171,6 +179,17 @@ PixelsMovement::PixelsMovement(
   }
 }
 
+PixelsMovement::~PixelsMovement()
+{
+  // Restore and Unlock the TilemapMode at the time of the
+  // PixelMovement creation.
```
Comment (martincapello) [inline src/app/ui/editor/pixels_movement.cpp:185]: Did you mean destruction?

Comment (Gasparoken) [reply src/app/ui/editor/pixels_movement.cpp:185]: I mean "Restore the TilemapMode that was saved during the PixelMovement build".
Maybe "Restore Tilemap mode" is enough to describe the idea.
I'll change the comment.

**Comment by Gasparoken** [comment]
Ready for the last review.

File: src/app/ui/editor/editor.h [hunk 2]
```diff
@@ -124,6 +124,13 @@ namespace app {
     // Returns the current state.
     EditorStatePtr getState() { return m_state; }
 
+    ColorBar* colorBar() {
+    #ifdef ENABLE_UI
+      return ColorBar::instance();
+    #endif
+      return nullptr;
+    }
+
```
Comment (dacap) [inline src/app/ui/editor/editor.h:133]: Remove this function and just use `ColorBar::instance()` when it's needed.

File: src/app/ui/editor/pixels_movement.cpp [hunk 3]
```diff
@@ -112,24 +112,32 @@ PixelsMovement::InnerCmd::MakeStamp(const Transformation& t)
...
   Context* context,
-  Site site,
+  Editor* editor,
   const Image* moveThis,
   const Mask* mask,
   const char* operationName)
   : m_reader(context)
-  , m_site(site)
-  , m_document(site.document())
+  , m_editor(editor)
```
Comment (dacap) [inline src/app/ui/editor/pixels_movement.cpp:120]: It looks like the `Site` parameter was changed by an `Editor` but the editor is being used only to access to the `ColorBar` (which can be already accessed through `ColorBar::instance()`). Not sure if this change is needed.

File: src/app/ui/editor/pixels_movement.cpp [hunk 4]
```diff
@@ -369,14 +392,27 @@ void PixelsMovement::moveImage(const gfx::PointF& pos, MoveModifier moveModifier
   gfx::RectF bounds = m_initialData.bounds();
   gfx::PointF abs_initial_pivot = m_initialData.pivot();
   gfx::PointF abs_pivot = m_currentData.pivot();
+  const bool tilesMode = m_site.tilemapMode() == TilemapMode::Tiles;
```
Comment (dacap) [inline src/app/ui/editor/pixels_movement.cpp:395]:
```suggestion
  const bool tilesMode = (m_site.tilemapMode() == TilemapMode::Tiles);
```
Please use `(...)` for these cases.

File: src/app/ui/editor/pixels_movement.cpp [hunk 5]
```diff
@@ -369,14 +392,27 @@ void PixelsMovement::moveImage(const gfx::PointF& pos, MoveModifier moveModifier
...
       double dx, dy;
-      if ((moveModifier & FineControl) == 0) {
+      if (tilesMode) {
+        if (m_catchPos.x == 0 && m_catchPos.y == 0) {
+          // Movement through keyboard:
+          dx = (pos.x - m_catchPos.x) * m_site.gridBounds().w;
+          dy = (pos.y - m_catchPos.y) * m_site.gridBounds().h;
+        }
+        else {
+          // Movement through mouse/trackpad:
```
Comment (dacap) [inline src/app/ui/editor/pixels_movement.cpp:410]: Can we use the `snap_to_grid()` logic for tihs case?

File: src/app/ui/editor/pixels_movement.cpp [hunk 6]
```diff
@@ -391,28 +427,9 @@ void PixelsMovement::moveImage(const gfx::PointF& pos, MoveModifier moveModifier
         else
           dy = 0.0;
       }
-
       bounds.offset(dx, dy);
-
-      if ((m_site.tilemapMode() == TilemapMode::Tiles) ||
-          (moveModifier & SnapToGridMovement) == SnapToGridMovement) {
```
Comment (dacap) [inline src/app/ui/editor/pixels_movement.cpp:398]: Why this was removed? It looks like now we cannot snap to grid when moving pixels when we press <kbd>Alt</kbd> key.

File: src/app/ui/editor/pixels_movement.cpp [hunk 7]
```diff
@@ -789,32 +849,106 @@ void PixelsMovement::stampImage(bool finalStamp)
...
+  TilemapMode originalSiteTilemapMode = (
+    m_site.tilemapMode() == TilemapMode::Tiles &&
+    m_site.layer()->isTilemap()? TilemapMode::Tiles : TilemapMode::Pixels);
+  TilesetMode originalSiteTilesetMode = m_site.tilesetMode();
+  auto initialMask0 = std::make_unique<Mask>(*m_initialMask0);
+  auto initialMask  = std::make_unique<Mask>(*m_initialMask);
+  auto currentMask  = std::make_unique<Mask>(*m_currentMask);
+  auto initialData  = std::make_unique<Transformation>(m_initialData);
+  auto currentData  = std::make_unique<Transformation>(m_currentData);
+
```
Comment (dacap) [inline src/app/ui/editor/pixels_movement.cpp:871]: Sometimes `Mask` can be just a value (not a pointer), the same for `Transformation`:
```suggestion
  Mask initialMask(*m_initialMask0);
  Mask initialMask(*m_initialMask);
  Mask currentMask(*m_currentMask);
  auto initialData = m_initialData;
  auto currentData = m_currentData;

```

File: src/doc/grid.h [hunk 8]
```diff
@@ -75,6 +76,9 @@ namespace doc {
     // Returns an array of tile positions that are touching the given region in the canvas
     std::vector<gfx::Point> tilesInCanvasRegion(const gfx::Region& rgn) const;
 
+    // Returns a mask aligned to the current grid, starting from other not aligned mask
+    Mask makeAlignedMask(const Mask* mask) const;
```
Comment (dacap) [inline src/doc/grid.h:80]: This function seems more related to masks than grids (e.g. a `Mask` constructor). There are two options: 1) move this function as a member function of the Mask class, or 2) create an utility function that receives both the mask and the grid as parameters (see `doc/util.h`).

**Review by dacap — CHANGES_REQUESTED** [review]
I've made some comments and some changes are required. I've just pushed a rebased version of your branch here: https://github.com/dacap/aseprite/tree/tilemap-multiple-move fixing some conflicts.

Continue from there, i.e. pull those changes and hard reset your `tilemap-multiple-move` head there.

File: src/app/ui/color_bar.cpp [hunk 9]
```diff
@@ -824,6 +824,16 @@ void ColorBar::onTilesButtonClick()
                                             TilemapMode::Pixels));
 }
 
+void ColorBar::enableTilemapModeButton(bool state)
+{
+  m_tilesButton.setEnabled(state);
+}
+
```
[the remark this answers is not in the document]
Comment (Gasparoken) [reply src/app/ui/color_bar.cpp:831]: Oh, I see. I prefer to lock Tilemap Mode, otherwise an accidental `Spacebar + Tab` can mess up the tileset without notice it on the canvas. Do you agree?
For the moment, I modified `MovingPixelsState::onBeforeCommandExecution` to not drop the pixels if the command is `CommandId::ToggleTilesMode()` + `ToggleTilesModeCommand` is locked while the Tilemap Mode toggle button is disabled.

**Comment by Gasparoken** [comment]
Ready for a new review.

**Comment by Gasparoken** [comment]
Due to conflicts on `pixels_movement`, I'll update the PR.

**Comment by dacap** [comment]
@Gasparoken please check @aseprite-bot comments and when it's ready I can review this.

**Comment by Gasparoken** [comment]
> @Gasparoken please check @aseprite-bot comments and when it's ready I can review this.

Ready for review.

**Comment by dacap** [comment]
I'm just testing and it works great :+1:

I think 164b938f3b50ab5cb5bcfce8c7181f11550d5d37 has a typo (tilemapMode two times).

There are other minor things (we prefer "TODO" instead of "TO DO", I checked that you have used "TO DO" in the past but we label this kind of comments as "TODO").

I'll make more comments about a1c79eea97c6a503a4ec7f3f42695008d7b169ac right now.

File: src/app/ui/editor/moving_pixels_state.cpp [hunk 10]
```diff
@@ -737,7 +737,8 @@ void MovingPixelsState::onBeforeCommandExecution(CommandExecutionEvent& ev)
     }
   }
 
-  if (m_pixelsMovement)
+  if (m_pixelsMovement &&
+      ev.command()->id() != CommandId::ToggleTilesMode())
     dropPixels();
```
Comment (dacap) [inline src/app/ui/editor/moving_pixels_state.cpp:742]: Probably we can handle ToogleTilesMode here like the other commands:
```c++
  else if (command->id() == CommandId::ToggleTilesMode()) {
    ev.cancel();
    return;
  }
```

**Review by dacap — CHANGES_REQUESTED** [review]
Some minor changes, I tested and found something strange when inverting the direction of the scale:

multi-bug

Anyway I'd prefer to merge the fix as it is which is a lot better than the current version, and probably fix this bug with other PR.

File: src/app/ui/editor/pixels_movement.cpp [hunk 11]
```diff
@@ -763,6 +805,39 @@ void PixelsMovement::getDraggedImageCopy(std::unique_ptr<Image>& outputImage,
...
+    grid.alignBounds(gfx::Rect(m_initialData.bounds().x + deltaA.w,
+                               m_initialData.bounds().y + deltaA.h,
+                               1, 1)).origin();
+  int deltaH = deltaB.w - deltaA.w;
+  int deltaV = deltaB.h - deltaA.h;
+  const gfx::RectF currentDataBounds(
+    currentDataAlignedOrigin.x,
+    currentDataAlignedOrigin.y,
+    m_initialData.bounds().w + (deltaH == 0 ? 0 : deltaH),
+    m_initialData.bounds().h + (deltaV == 0 ? 0 : deltaV));
```
[the remark this answers is not in the document]
Comment (Gasparoken) [reply src/app/ui/editor/pixels_movement.cpp:837]: Haha! 😂  Yeah! This PR has been modified several times over time, perhaps at some point this condition contained more logic and made sense. I will obviously apply the recommendation.

**Comment by dacap** [comment]
Looks great! :+1:
